// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalg0l-yM4G2027jNcO76jmpZ5DXY01Os',
    appId: '1:47826687686:web:a1c5fc49f5da6e279aa9c7',
    messagingSenderId: '47826687686',
    projectId: 'controleabastecimentofelipe',
    authDomain: 'controleabastecimentofelipe.firebaseapp.com',
    storageBucket: 'controleabastecimentofelipe.firebasestorage.app',
    measurementId: 'G-P94VCNX2KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARvfIII2w840p6N50v619BRHBJQq6Zt20',
    appId: '1:47826687686:android:760bb92bdeb7580e9aa9c7',
    messagingSenderId: '47826687686',
    projectId: 'controleabastecimentofelipe',
    storageBucket: 'controleabastecimentofelipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnpIx6t4FSd5D9D5b7IaedOcIKTLykydI',
    appId: '1:47826687686:ios:6cff745db8158a2f9aa9c7',
    messagingSenderId: '47826687686',
    projectId: 'controleabastecimentofelipe',
    storageBucket: 'controleabastecimentofelipe.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnpIx6t4FSd5D9D5b7IaedOcIKTLykydI',
    appId: '1:47826687686:ios:6cff745db8158a2f9aa9c7',
    messagingSenderId: '47826687686',
    projectId: 'controleabastecimentofelipe',
    storageBucket: 'controleabastecimentofelipe.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalg0l-yM4G2027jNcO76jmpZ5DXY01Os',
    appId: '1:47826687686:web:57a5761a99f617099aa9c7',
    messagingSenderId: '47826687686',
    projectId: 'controleabastecimentofelipe',
    authDomain: 'controleabastecimentofelipe.firebaseapp.com',
    storageBucket: 'controleabastecimentofelipe.firebasestorage.app',
    measurementId: 'G-BM0ZTD3S29',
  );
}
